version: "3.9"

services:
  backend:
    build:
      context: ../../backend
      dockerfile: ../scripts/backend/Dockerfile
    container_name: iotiq_backend
    env_file:
      - ../../backend/.env
    ports:
      - "5000:5000"
    restart: always
    networks:
      - iotiq_network

networks:
  iotiq_network:
    driver: bridge
